// Auto-generated by scripts/build-docs-index.ts
// Do not edit manually - run: bun run build:docs

export const slugToPath: Record<string, string> = {
	"signals": "concepts/signals.md",
	"05-testing-progression": "tutorials/05-testing-progression.md",
	"03-synthesis": "tutorials/03-synthesis.md",
	"02-filters": "tutorials/02-filters.md",
	"04-rhythm": "tutorials/04-rhythm.md",
	"01-hello-sine": "tutorials/01-hello-sine.md",
	"microtonal": "reference/mini-notation/microtonal.md",
	"basics": "reference/mini-notation/basics.md",
	"conditionals": "reference/language/conditionals.md",
	"pipes": "reference/language/pipes.md",
	"arrays": "reference/language/arrays.md",
	"variables": "reference/language/variables.md",
	"closures": "reference/language/closures.md",
	"operators": "reference/language/operators.md",
	"stereo": "reference/builtins/stereo.md",
	"sequencing": "reference/builtins/sequencing.md",
	"delays": "reference/builtins/delays.md",
	"filters": "reference/builtins/filters.md",
	"distortion": "reference/builtins/distortion.md",
	"utility": "reference/builtins/utility.md",
	"envelopes": "reference/builtins/envelopes.md",
	"modulation": "reference/builtins/modulation.md",
	"math": "reference/builtins/math.md",
	"oscillators": "reference/builtins/oscillators.md",
	"dynamics": "reference/builtins/dynamics.md",
	"reverbs": "reference/builtins/reverbs.md",
	"visualizations": "reference/builtins/visualizations.md",
	"DOCUMENTATION_GUIDE": "DOCUMENTATION_GUIDE.md"
};

export const navigation: Record<string, Array<{ slug: string; title: string }>> = {
	"tutorials": [
		{
			"slug": "01-hello-sine",
			"title": "Hello Sine"
		},
		{
			"slug": "02-filters",
			"title": "Shaping Sound with Filters"
		},
		{
			"slug": "03-synthesis",
			"title": "Building Synth Voices"
		},
		{
			"slug": "04-rhythm",
			"title": "Rhythm & Patterns"
		},
		{
			"slug": "05-testing-progression",
			"title": "Testing Progression"
		}
	],
	"builtins": [
		{
			"slug": "oscillators",
			"title": "Oscillators"
		},
		{
			"slug": "filters",
			"title": "Filters"
		},
		{
			"slug": "envelopes",
			"title": "Envelopes"
		},
		{
			"slug": "sequencing",
			"title": "Sequencing & Timing"
		},
		{
			"slug": "delays",
			"title": "Delays"
		},
		{
			"slug": "reverbs",
			"title": "Reverbs"
		},
		{
			"slug": "modulation",
			"title": "Modulation Effects"
		},
		{
			"slug": "distortion",
			"title": "Distortion"
		},
		{
			"slug": "dynamics",
			"title": "Dynamics"
		},
		{
			"slug": "math",
			"title": "Math Functions"
		},
		{
			"slug": "utility",
			"title": "Utility"
		},
		{
			"slug": "stereo",
			"title": "Stereo"
		},
		{
			"slug": "visualizations",
			"title": "Visualizations"
		}
	],
	"language": [
		{
			"slug": "pipes",
			"title": "Pipes & Holes"
		},
		{
			"slug": "variables",
			"title": "Variables & Assignment"
		},
		{
			"slug": "operators",
			"title": "Operators"
		},
		{
			"slug": "closures",
			"title": "Closures"
		},
		{
			"slug": "conditionals",
			"title": "Conditionals & Logic"
		},
		{
			"slug": "arrays",
			"title": "Arrays"
		}
	],
	"mini-notation": [
		{
			"slug": "basics",
			"title": "Mini-Notation Basics"
		},
		{
			"slug": "microtonal",
			"title": "Microtonal Notation"
		}
	],
	"concepts": [
		{
			"slug": "DOCUMENTATION_GUIDE",
			"title": "Documentation Guide"
		},
		{
			"slug": "signals",
			"title": "Mono & Stereo Signals"
		}
	]
};

export const lookup: Record<string, { slug: string; category: string; title: string; anchor?: string }> = {
	"mono": {
		"slug": "stereo",
		"category": "builtins",
		"title": "mono",
		"anchor": "mono"
	},
	"stereo": {
		"slug": "stereo",
		"category": "builtins",
		"title": "stereo",
		"anchor": "stereo"
	},
	"channels": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"auto-lift": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Auto-lift",
		"anchor": "auto-lift"
	},
	"conversion": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"downmix": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"upmix": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"signal types": {
		"slug": "signals",
		"category": "concepts",
		"title": "Mono & Stereo Signals"
	},
	"testing": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"patterns": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"synthesis": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"triggers": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"envelopes": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"samples": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"filters": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"moog": {
		"slug": "filters",
		"category": "builtins",
		"title": "moog",
		"anchor": "moog"
	},
	"diode": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"sallenkey": {
		"slug": "filters",
		"category": "builtins",
		"title": "sallenkey",
		"anchor": "sallenkey"
	},
	"formant": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"distortion": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"saturate": {
		"slug": "distortion",
		"category": "builtins",
		"title": "saturate",
		"anchor": "saturate"
	},
	"bitcrush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "bitcrush",
		"anchor": "bitcrush"
	},
	"fold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "fold",
		"anchor": "fold"
	},
	"tube": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tube",
		"anchor": "tube"
	},
	"tape": {
		"slug": "distortion",
		"category": "builtins",
		"title": "tape",
		"anchor": "tape"
	},
	"xfmr": {
		"slug": "distortion",
		"category": "builtins",
		"title": "xfmr",
		"anchor": "xfmr"
	},
	"excite": {
		"slug": "distortion",
		"category": "builtins",
		"title": "excite",
		"anchor": "excite"
	},
	"chorus": {
		"slug": "modulation",
		"category": "builtins",
		"title": "chorus",
		"anchor": "chorus"
	},
	"flanger": {
		"slug": "modulation",
		"category": "builtins",
		"title": "flanger",
		"anchor": "flanger"
	},
	"phaser": {
		"slug": "modulation",
		"category": "builtins",
		"title": "phaser",
		"anchor": "phaser"
	},
	"comb": {
		"slug": "modulation",
		"category": "builtins",
		"title": "comb",
		"anchor": "comb"
	},
	"reverb": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"freeverb": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "freeverb",
		"anchor": "freeverb"
	},
	"dattorro": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "dattorro",
		"anchor": "dattorro"
	},
	"fdn": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "fdn",
		"anchor": "fdn"
	},
	"delay": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay",
		"anchor": "delay"
	},
	"comp": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "comp",
		"anchor": "comp"
	},
	"limiter": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "limiter",
		"anchor": "limiter"
	},
	"gate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "gate",
		"anchor": "gate"
	},
	"slew": {
		"slug": "utility",
		"category": "builtins",
		"title": "slew",
		"anchor": "slew"
	},
	"sah": {
		"slug": "utility",
		"category": "builtins",
		"title": "sah",
		"anchor": "sah"
	},
	"lfo": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "lfo",
		"anchor": "lfo"
	},
	"env_follower": {
		"slug": "05-testing-progression",
		"category": "tutorials",
		"title": "Testing Progression"
	},
	"synth": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"envelope": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"adsr": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "adsr",
		"anchor": "adsr"
	},
	"ar": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "ar",
		"anchor": "ar"
	},
	"subtractive": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"tutorial": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"voice": {
		"slug": "03-synthesis",
		"category": "tutorials",
		"title": "Building Synth Voices"
	},
	"filter": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lowpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"highpass": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"cutoff": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"resonance": {
		"slug": "02-filters",
		"category": "tutorials",
		"title": "Shaping Sound with Filters"
	},
	"lp": {
		"slug": "filters",
		"category": "builtins",
		"title": "lp",
		"anchor": "lp"
	},
	"hp": {
		"slug": "filters",
		"category": "builtins",
		"title": "hp",
		"anchor": "hp"
	},
	"rhythm": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"pattern": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"beat": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"trigger": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "trigger",
		"anchor": "trigger"
	},
	"euclidean": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"sequencer": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"clock": {
		"slug": "utility",
		"category": "builtins",
		"title": "clock",
		"anchor": "clock"
	},
	"select": {
		"slug": "conditionals",
		"category": "language",
		"title": "select",
		"anchor": "select"
	},
	"conditional": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"threshold": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"and": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"or": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"not": {
		"slug": "04-rhythm",
		"category": "tutorials",
		"title": "Rhythm & Patterns"
	},
	"getting started": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"first sound": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"sine": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"oscillator": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"output": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"beginner": {
		"slug": "01-hello-sine",
		"category": "tutorials",
		"title": "Hello Sine"
	},
	"osc": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "osc",
		"anchor": "osc"
	},
	"microtonal": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"tuning": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"quarter tone": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"17edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"24edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"31edo": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"tune": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"xenharmonic": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"cents": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"micro-step": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"step up": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"step down": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"caret": {
		"slug": "microtonal",
		"category": "mini-notation",
		"title": "Microtonal Notation"
	},
	"mini-notation": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"sequence": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"pitch": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"chord": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"rest": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"tidal": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"strudel": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"modifier": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"speed": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"slow": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"repeat": {
		"slug": "arrays",
		"category": "language",
		"title": "repeat",
		"anchor": "repeat"
	},
	"chance": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"alternation": {
		"slug": "basics",
		"category": "mini-notation",
		"title": "Mini-Notation Basics"
	},
	"truth convention": {
		"slug": "conditionals",
		"category": "language",
		"title": "Truth Convention",
		"anchor": "truth-convention"
	},
	"gt": {
		"slug": "conditionals",
		"category": "language",
		"title": "gt",
		"anchor": "gt"
	},
	"lt": {
		"slug": "conditionals",
		"category": "language",
		"title": "lt",
		"anchor": "lt"
	},
	"gte": {
		"slug": "conditionals",
		"category": "language",
		"title": "gte",
		"anchor": "gte"
	},
	"lte": {
		"slug": "conditionals",
		"category": "language",
		"title": "lte",
		"anchor": "lte"
	},
	"eq": {
		"slug": "conditionals",
		"category": "language",
		"title": "eq",
		"anchor": "eq"
	},
	"neq": {
		"slug": "conditionals",
		"category": "language",
		"title": "neq",
		"anchor": "neq"
	},
	"band": {
		"slug": "conditionals",
		"category": "language",
		"title": "band",
		"anchor": "band"
	},
	"bor": {
		"slug": "conditionals",
		"category": "language",
		"title": "bor",
		"anchor": "bor"
	},
	"bnot": {
		"slug": "conditionals",
		"category": "language",
		"title": "bnot",
		"anchor": "bnot"
	},
	"see also": {
		"slug": "conditionals",
		"category": "language",
		"title": "See Also",
		"anchor": "see-also"
	},
	"conditionals": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"logic": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"comparison": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"ternary": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"if": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"else": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"boolean": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"equal": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"equality": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"greater": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"less": {
		"slug": "conditionals",
		"category": "language",
		"title": "Conditionals & Logic"
	},
	"pipe": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"hole": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"|>": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"%": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"signal flow": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"graph": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"connection": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"routing": {
		"slug": "pipes",
		"category": "language",
		"title": "Pipes & Holes"
	},
	"array literals": {
		"slug": "arrays",
		"category": "language",
		"title": "Array Literals",
		"anchor": "array-literals"
	},
	"indexing": {
		"slug": "arrays",
		"category": "language",
		"title": "Indexing",
		"anchor": "indexing"
	},
	"auto-expansion via map and sum": {
		"slug": "arrays",
		"category": "language",
		"title": "Auto-Expansion via map and sum",
		"anchor": "auto-expansion-via-map-and-sum"
	},
	"len": {
		"slug": "arrays",
		"category": "language",
		"title": "len",
		"anchor": "len"
	},
	"map": {
		"slug": "arrays",
		"category": "language",
		"title": "map",
		"anchor": "map"
	},
	"reduce": {
		"slug": "arrays",
		"category": "language",
		"title": "reduce",
		"anchor": "reduce"
	},
	"zipwith": {
		"slug": "arrays",
		"category": "language",
		"title": "zipWith",
		"anchor": "zipwith"
	},
	"zip": {
		"slug": "arrays",
		"category": "language",
		"title": "zip",
		"anchor": "zip"
	},
	"take": {
		"slug": "arrays",
		"category": "language",
		"title": "take",
		"anchor": "take"
	},
	"drop": {
		"slug": "arrays",
		"category": "language",
		"title": "drop",
		"anchor": "drop"
	},
	"reverse": {
		"slug": "arrays",
		"category": "language",
		"title": "reverse",
		"anchor": "reverse"
	},
	"sum": {
		"slug": "arrays",
		"category": "language",
		"title": "sum",
		"anchor": "sum"
	},
	"mean": {
		"slug": "arrays",
		"category": "language",
		"title": "mean",
		"anchor": "mean"
	},
	"rotate": {
		"slug": "arrays",
		"category": "language",
		"title": "rotate",
		"anchor": "rotate"
	},
	"shuffle": {
		"slug": "arrays",
		"category": "language",
		"title": "shuffle",
		"anchor": "shuffle"
	},
	"sort": {
		"slug": "arrays",
		"category": "language",
		"title": "sort",
		"anchor": "sort"
	},
	"normalize": {
		"slug": "arrays",
		"category": "language",
		"title": "normalize",
		"anchor": "normalize"
	},
	"scale": {
		"slug": "arrays",
		"category": "language",
		"title": "scale",
		"anchor": "scale"
	},
	"range": {
		"slug": "arrays",
		"category": "language",
		"title": "range",
		"anchor": "range"
	},
	"linspace": {
		"slug": "arrays",
		"category": "language",
		"title": "linspace",
		"anchor": "linspace"
	},
	"random": {
		"slug": "arrays",
		"category": "language",
		"title": "random",
		"anchor": "random"
	},
	"harmonics": {
		"slug": "arrays",
		"category": "language",
		"title": "harmonics",
		"anchor": "harmonics"
	},
	"polyphony builtins": {
		"slug": "arrays",
		"category": "language",
		"title": "Polyphony Builtins",
		"anchor": "polyphony-builtins"
	},
	"common patterns": {
		"slug": "arrays",
		"category": "language",
		"title": "Common Patterns",
		"anchor": "common-patterns"
	},
	"array": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"list": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"arrays": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"length": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"average": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"polyphony": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"voices": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"multi-buffer": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"comprehension": {
		"slug": "arrays",
		"category": "language",
		"title": "Arrays"
	},
	"variables": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"assignment": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"let": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"binding": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"scope": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"identifier": {
		"slug": "variables",
		"category": "language",
		"title": "Variables & Assignment"
	},
	"closures": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"functions": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"lambda": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"anonymous": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"arrow": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"callback": {
		"slug": "closures",
		"category": "language",
		"title": "Closures"
	},
	"operators": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"precedence": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"arithmetic": {
		"slug": "math",
		"category": "builtins",
		"title": "Arithmetic",
		"anchor": "arithmetic"
	},
	"plus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"minus": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"multiply": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"divide": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"power": {
		"slug": "operators",
		"category": "language",
		"title": "Operators"
	},
	"left, right": {
		"slug": "stereo",
		"category": "builtins",
		"title": "left, right",
		"anchor": "left-right"
	},
	"pan": {
		"slug": "stereo",
		"category": "builtins",
		"title": "pan",
		"anchor": "pan"
	},
	"width": {
		"slug": "stereo",
		"category": "builtins",
		"title": "width",
		"anchor": "width"
	},
	"ms_encode, ms_decode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "ms_encode, ms_decode",
		"anchor": "ms-encode-ms-decode"
	},
	"pingpong": {
		"slug": "stereo",
		"category": "builtins",
		"title": "pingpong",
		"anchor": "pingpong"
	},
	"left": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"right": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"ms_encode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"ms_decode": {
		"slug": "stereo",
		"category": "builtins",
		"title": "Stereo"
	},
	"euclid": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "euclid",
		"anchor": "euclid"
	},
	"timeline": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "timeline",
		"anchor": "timeline"
	},
	"sequencing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"timing": {
		"slug": "sequencing",
		"category": "builtins",
		"title": "Sequencing & Timing"
	},
	"delay_ms": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay_ms",
		"anchor": "delay-ms"
	},
	"delay_smp": {
		"slug": "delays",
		"category": "builtins",
		"title": "delay_smp",
		"anchor": "delay-smp"
	},
	"tap_delay": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay",
		"anchor": "tap-delay"
	},
	"tap_delay_ms": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay_ms",
		"anchor": "tap-delay-ms"
	},
	"tap_delay_smp": {
		"slug": "delays",
		"category": "builtins",
		"title": "tap_delay_smp",
		"anchor": "tap-delay-smp"
	},
	"echo": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"feedback": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"time": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"fb": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"effect": {
		"slug": "delays",
		"category": "builtins",
		"title": "Delays"
	},
	"bp": {
		"slug": "filters",
		"category": "builtins",
		"title": "bp",
		"anchor": "bp"
	},
	"bandpass": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"svf": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"q": {
		"slug": "filters",
		"category": "builtins",
		"title": "Filters"
	},
	"softclip": {
		"slug": "distortion",
		"category": "builtins",
		"title": "softclip",
		"anchor": "softclip"
	},
	"smooth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "smooth",
		"anchor": "smooth"
	},
	"wavefold": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"drive": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"crush": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"lofi": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"valve": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"adaa": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"warmth": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"transformer": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"exciter": {
		"slug": "distortion",
		"category": "builtins",
		"title": "Distortion"
	},
	"out": {
		"slug": "utility",
		"category": "builtins",
		"title": "out",
		"anchor": "out"
	},
	"mtof": {
		"slug": "utility",
		"category": "builtins",
		"title": "mtof",
		"anchor": "mtof"
	},
	"dc": {
		"slug": "utility",
		"category": "builtins",
		"title": "dc",
		"anchor": "dc"
	},
	"utility": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"midi": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"frequency": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"sample": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"hold": {
		"slug": "utility",
		"category": "builtins",
		"title": "Utility"
	},
	"attack": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"decay": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"sustain": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"release": {
		"slug": "envelopes",
		"category": "builtins",
		"title": "Envelopes"
	},
	"modulation": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"rate": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"depth": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"sweep": {
		"slug": "modulation",
		"category": "builtins",
		"title": "Modulation Effects"
	},
	"unary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Unary Math",
		"anchor": "unary-math"
	},
	"binary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Binary Math",
		"anchor": "binary-math"
	},
	"ternary math": {
		"slug": "math",
		"category": "builtins",
		"title": "Ternary Math",
		"anchor": "ternary-math"
	},
	"trigonometric functions": {
		"slug": "math",
		"category": "builtins",
		"title": "Trigonometric Functions",
		"anchor": "trigonometric-functions"
	},
	"hyperbolic functions": {
		"slug": "math",
		"category": "builtins",
		"title": "Hyperbolic Functions",
		"anchor": "hyperbolic-functions"
	},
	"math": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"add": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sub": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"mul": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"div": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"pow": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"neg": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"abs": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sqrt": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"log": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"exp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"floor": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"ceil": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"min": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"max": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"clamp": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"wrap": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sin": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"cos": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"tan": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"asin": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"acos": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"atan": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"atan2": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"sinh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"cosh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"tanh": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"trigonometry": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"hyperbolic": {
		"slug": "math",
		"category": "builtins",
		"title": "Math Functions"
	},
	"tri": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"triangle": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"saw": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sawtooth": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"sqr": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"square": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"phasor": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"ramp": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"noise": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"waveform": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "waveform",
		"anchor": "waveform"
	},
	"tone": {
		"slug": "oscillators",
		"category": "builtins",
		"title": "Oscillators"
	},
	"dynamics": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compressor": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"noisegate": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ratio": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"ceiling": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"compression": {
		"slug": "dynamics",
		"category": "builtins",
		"title": "Dynamics"
	},
	"room": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"plate": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"space": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"damping": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"wet": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"dry": {
		"slug": "reverbs",
		"category": "builtins",
		"title": "Reverbs"
	},
	"oscilloscope": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "oscilloscope",
		"anchor": "oscilloscope"
	},
	"spectrum": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "spectrum",
		"anchor": "spectrum"
	},
	"waterfall": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "waterfall",
		"anchor": "waterfall"
	},
	"pianoroll": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "pianoroll",
		"anchor": "pianoroll"
	},
	"visualization": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"viz": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"piano": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"roll": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"display": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"monitor": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"probe": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"fft": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"spectrogram": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"logscale": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"mindb": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"maxdb": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"filled": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"showgrid": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"gradient": {
		"slug": "visualizations",
		"category": "builtins",
		"title": "Visualizations"
	},
	"contributing": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"documentation": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"guide": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	},
	"standards": {
		"slug": "DOCUMENTATION_GUIDE",
		"category": "concepts",
		"title": "Documentation Guide"
	}
};

export const previews: Record<string, string> = {
	"signals": "Akkado has two kinds of audio signals: Mono (one channel) and Stereo (two channels, L and R). Every expression the compiler sees has a known...",
	"05-testing-progression": "Work through each level in order. Report back which levels work, fail, or have issues.",
	"03-synthesis": "Now that you know oscillators and filters, let's combine them into complete synthesizer voices with amplitude envelopes.",
	"02-filters": "Filters are essential tools for sculpting your sounds. They remove or emphasize certain frequencies, transforming raw oscillators into musical...",
	"04-rhythm": "Music is about time. In this tutorial, you'll learn to create rhythmic patterns, from basic beats to complex polyrhythms.",
	"01-hello-sine": "Welcome to Akkado! In this tutorial, you'll make your first sound and learn the basics of how the language works.",
	"microtonal": "Akkado supports microtonal pitch notation through micro-step operators (, , ) and the  function, which selects how those operators map to frequency.",
	"basics": "Mini-notation is a compact syntax for describing musical patterns, inspired by TidalCycles and Strudel.",
	"conditionals": "Signal-rate decision-making: compare signals, combine boolean signals with AND/OR/NOT, and pick between two signals based on a condition. Every...",
	"pipes": "The pipe operator () and hole () are the foundation of Akkado's signal flow model.",
	"arrays": "Arrays are ordered, fixed-size collections of values. They are the primary way to express parallel signal flows in Akkado: every element of an...",
	"variables": "Variables store values for reuse throughout your patch.",
	"closures": "Closures are anonymous functions that capture their environment. They're the bridge between patterns and synthesis.",
	"operators": "Akkado uses operators for arithmetic, comparison, logic, and signal flow.",
	"stereo": "Stereo signal operations. Akkado tracks channel count (Mono vs Stereo) on every signal; mono DSP ops applied to a stereo signal auto-lift — a...",
	"sequencing": "Timing and sequencing functions create rhythmic patterns, triggers, and automation curves synchronized to the global clock.",
	"delays": "Delay effects create copies of a signal offset in time, enabling echoes, rhythmic effects, and spatial depth.",
	"filters": "Filters shape the frequency content of signals by attenuating or boosting certain frequencies.",
	"distortion": "Distortion effects add harmonic content by clipping, saturating, or otherwise mangling signals.",
	"utility": "Utility functions for common audio tasks like output, MIDI conversion, and signal processing helpers.",
	"envelopes": "Envelopes shape the amplitude or other parameters of a sound over time. They respond to gates (sustained signals) or triggers (momentary pulses).",
	"modulation": "Modulation effects use time-varying delays to create movement and spatial interest in sounds.",
	"math": "Mathematical operations for signal processing and control logic.",
	"oscillators": "Oscillators are the fundamental sound sources in synthesis. The  function is the unified interface for all oscillator types.",
	"dynamics": "Dynamics processors control the volume envelope of signals, reducing dynamic range or removing unwanted quiet sections.",
	"reverbs": "Reverbs simulate acoustic spaces by creating many delayed, filtered reflections. Different algorithms offer different sonic characteristics.",
	"visualizations": "Inline visualizations that render directly in the editor. Each visualization is inserted as a pass-through node in the signal chain — the audio...",
	"DOCUMENTATION_GUIDE": "This guide outlines standards and practices for writing NKIDO documentation."
};
