"""Emit Akkado source from a parsed + quantized song."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from . import gm
from .midi_reader import SongIR
from .mini_notation import Slot, slots_to_pattern
from .quantize import (
    quantize_voice,
    slots_per_beat,
    total_bars_for_song,
)
from .voice_split import VoiceIR, split_track

VALID_IDENT_RE = re.compile(r"[^a-z0-9_]+")


def _sanitize_ident(raw: str) -> str:
    ident = VALID_IDENT_RE.sub("_", raw.lower()).strip("_")
    if not ident:
        ident = "track"
    if ident[0].isdigit():
        ident = "t_" + ident
    return ident


def _uniquify(base: str, taken: set[str]) -> str:
    if base not in taken:
        taken.add(base)
        return base
    i = 2
    while f"{base}_{i}" in taken:
        i += 1
    name = f"{base}_{i}"
    taken.add(name)
    return name


@dataclass
class EmittedVoice:
    name: str
    pattern: str
    program: int
    is_drum: bool
    track_name: str
    voice_index: int       # 1-based within the track
    voice_count: int       # total voices for the parent track
    dropped_notes: int


@dataclass
class EmittedSong:
    voices: list[EmittedVoice]
    total_bars: int
    bpm: float
    time_sig: tuple[int, int]
    slots_per_bar: int
    subdivision: int
    source_path: str


def prepare(
    song: SongIR,
    subdivision: int = 16,
    max_voices: int = 4,
) -> EmittedSong:
    """Split, quantize, and assemble EmittedVoices from a SongIR."""
    # MIDI ticks_per_beat is always "ticks per quarter note". Convert the
    # time signature into quarter notes per bar:
    #   4/4 -> 4, 3/4 -> 3, 6/8 -> 3, 2/2 -> 4
    # We use a non-integer-safe round because denominator=1 is legal.
    quarters_per_bar = max(1, int(round(song.time_sig_num * 4 / song.time_sig_den)))

    spb = slots_per_beat(subdivision)
    slots_per_bar = spb * quarters_per_bar
    beats_per_bar = quarters_per_bar

    last_end_tick = 0
    for t in song.tracks:
        for n in t.notes:
            last_end_tick = max(last_end_tick, n.start_tick + n.duration_ticks)
    total_bars = total_bars_for_song(last_end_tick, song.ticks_per_beat, beats_per_bar)

    taken_names: set[str] = set()
    voices: list[EmittedVoice] = []

    for track in song.tracks:
        split = split_track(track, max_voices=max_voices)
        base_ident = _sanitize_ident(track.name)
        voice_count = len(split.voices)

        for v in split.voices:
            slots, collisions = quantize_voice(
                v,
                ticks_per_beat=song.ticks_per_beat,
                subdivision=subdivision,
                slots_per_bar=slots_per_bar,
                total_bars=total_bars,
            )
            pattern = slots_to_pattern(slots, slots_per_bar)

            suffix = f"_v{v.voice_index + 1}" if voice_count > 1 else ""
            name = _uniquify(f"{base_ident}{suffix}", taken_names)

            voices.append(EmittedVoice(
                name=name,
                pattern=pattern,
                program=track.program,
                is_drum=track.is_drum,
                track_name=track.name,
                voice_index=v.voice_index + 1,
                voice_count=voice_count,
                dropped_notes=split.dropped_count + collisions,
            ))

    return EmittedSong(
        voices=voices,
        total_bars=total_bars,
        bpm=song.bpm,
        time_sig=(song.time_sig_num, song.time_sig_den),
        slots_per_bar=slots_per_bar,
        subdivision=subdivision,
        source_path=song.source_path,
    )


def render(
    song: EmittedSong,
    soundfont: str = "GM.sf3",
    instrument: str = "soundfont",
) -> str:
    """Render an EmittedSong as Akkado source."""
    if instrument not in ("soundfont", "osc"):
        raise ValueError(f"unknown instrument: {instrument}")

    lines: list[str] = []
    src = Path(song.source_path).name
    lines.append(f"// Generated by midi2akk from {src}")
    lines.append(
        f"// Tempo: {song.bpm:.2f} bpm, time signature: "
        f"{song.time_sig[0]}/{song.time_sig[1]}, bars: {song.total_bars}, "
        f"subdivision: 1/{song.subdivision}"
    )
    lines.append(f"// Backend: {instrument}" + (f" ({soundfont})" if instrument == "soundfont" else ""))
    lines.append("")
    lines.append(f"bpm = {int(round(song.bpm))}")
    lines.append("")

    if not song.voices:
        lines.append("// (no notes found in input MIDI)")
        lines.append("0 |> out(%, %)")
        return "\n".join(lines) + "\n"

    for v in song.voices:
        if v.is_drum:
            label = "GM drum kit"
        else:
            label = f"program {v.program}: {gm.program_name(v.program)}"
        voice_label = (
            f" [voice {v.voice_index}/{v.voice_count}]"
            if v.voice_count > 1 else ""
        )
        lines.append(f"// {v.track_name}{voice_label} — {label}")
        if v.dropped_notes > 0:
            lines.append(f"//   warning: {v.dropped_notes} note(s) dropped "
                         f"(voice cap or quantize collision)")

        pipeline = _render_pipeline(v, soundfont=soundfont, instrument=instrument)
        lines.append(f"{v.name} = {pipeline}")
        lines.append("")

    mix_expr = _render_mix(song.voices)
    lines.append("// Mix down to stereo with even gain per track")
    lines.append(f"{mix_expr} |> out(%, %)")

    return "\n".join(lines) + "\n"


def _render_pipeline(voice: EmittedVoice, soundfont: str, instrument: str) -> str:
    pattern_call = f'pat("{voice.pattern}")'

    if instrument == "soundfont":
        preset = gm.DRUM_PRESET if voice.is_drum else voice.program
        return (
            f'{pattern_call}\n'
            f'  |> soundfont(%, "{soundfont}", {preset})'
        )

    # osc fallback — saw + ADSR, works today without the soundfont path.
    return (
        f'{pattern_call} as e\n'
        f'  |> osc("saw", e.freq)\n'
        f'  |> % * adsr(e.gate, 0.01, 0.1, 0.6, 0.3)\n'
        f'  |> % * e.vel'
    )


def _render_mix(voices: list[EmittedVoice]) -> str:
    if len(voices) == 1:
        return voices[0].name
    inner = " + ".join(v.name for v in voices)
    scale = f"(1.0 / {len(voices)})"
    return f"({inner}) * {scale}"


def convert(
    song: SongIR,
    *,
    subdivision: int = 16,
    max_voices: int = 4,
    soundfont: str = "GM.sf3",
    instrument: str = "soundfont",
) -> str:
    emitted = prepare(song, subdivision=subdivision, max_voices=max_voices)
    return render(emitted, soundfont=soundfont, instrument=instrument)
